kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cam-log
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      use: cam-log
      